/**
 * BRSR Core: the nine assured attributes, mapped to the framework questions that
 * carry them, with a plain-English definition and a worked example shown at the
 * point of entry. This drives the "Core first" view and the inline guidance.
 */

export interface CoreGuide {
  /** BRSR Core attribute this KPI belongs to (for grouping). */
  attribute: string;
  /** Order of the attribute in the official Core list. */
  order: number;
  definition: string;
  example: string;
}

export const CORE_GUIDANCE: Record<string, CoreGuide> = {
  "C.P6.EI.7": {
    attribute: "GHG footprint",
    order: 1,
    definition:
      "Total direct emissions (Scope 1) and emissions from purchased energy (Scope 2), in metric tonnes of CO2 equivalent, and their intensity per rupee of turnover (and PPP-adjusted).",
    example:
      "A plant burns 50,000 L diesel (Scope 1 ≈ 134 tCO2e) and buys 2,000,000 kWh grid electricity (Scope 2 ≈ 1,420 tCO2e): enter Scope 1 = 134, Scope 2 = 1,420.",
  },
  "C.P6.EI.3": {
    attribute: "Water footprint",
    order: 2,
    definition:
      "Water withdrawn by source (surface, ground, third-party, seawater, other) and total water consumed (withdrawal minus discharge), in kilolitres, with intensity per rupee of turnover.",
    example:
      "Withdraw 40,000 kL (30,000 ground + 10,000 third-party) and discharge 15,000 kL → total consumption = 25,000 kL.",
  },
  "C.P6.EI.1": {
    attribute: "Energy footprint",
    order: 3,
    definition:
      "Total energy consumed from renewable and non-renewable sources (electricity + fuel + other), in Joules or GJ, with intensity per rupee of turnover.",
    example:
      "1,200 GJ from renewable + 8,800 GJ from non-renewable sources = 10,000 GJ total energy consumed.",
  },
  "C.P6.EI.9": {
    attribute: "Circularity (waste)",
    order: 4,
    definition:
      "Total waste generated by category (plastic, e-waste, bio-medical, C&D, battery, radioactive, other hazardous / non-hazardous) in metric tonnes, split into recovered vs disposed, with intensity per turnover.",
    example:
      "Plastic 12 MT + hazardous 3 MT + other non-hazardous 40 MT = 55 MT generated; 45 MT recycled, 10 MT landfilled.",
  },
  "C.P3.EI.1c": {
    attribute: "Employee wellbeing & safety",
    order: 5,
    definition:
      "Total spend on employee and worker wellbeing measures (health/accident insurance, maternity/paternity, day-care, welfare) as a percentage of total revenue.",
    example:
      "₹1.2 crore of wellbeing spend on ₹50 crore revenue = 2.4%.",
  },
  "C.P3.EI.11": {
    attribute: "Employee wellbeing & safety",
    order: 5,
    definition:
      "Safety performance for employees and workers, including LTIFR = (lost-time injuries × 1,000,000) / total hours worked, total recordable work-related injuries, and number of fatalities.",
    example:
      "3 lost-time injuries over 1,500,000 hours worked → LTIFR = (3 × 1,000,000) / 1,500,000 = 2.0.",
  },
  "C.P5.EI.3b": {
    attribute: "Gender diversity",
    order: 6,
    definition:
      "Gross wages paid to female employees and workers as a percentage of the total gross wages paid by the entity.",
    example:
      "₹6 crore paid to women out of ₹30 crore total wages = 20%.",
  },
  "C.P5.EI.7": {
    attribute: "Gender diversity",
    order: 6,
    definition:
      "Complaints under the POSH Act: total sexual-harassment complaints reported, as a percentage of female headcount, and the number upheld.",
    example:
      "2 complaints across 120 women employees → 1.7%; 1 upheld.",
  },
  "C.P8.EI.4": {
    attribute: "Inclusive development",
    order: 7,
    definition:
      "Percentage of input material (by value) directly sourced from MSMEs / small producers, and directly sourced from within India.",
    example:
      "₹8 crore of ₹20 crore total inputs sourced from MSMEs = 40%.",
  },
  "C.P8.EI.5": {
    attribute: "Inclusive development",
    order: 7,
    definition:
      "Wages paid to persons employed as a percentage of total wage cost, split by RBI location class: rural, semi-urban, urban and metropolitan.",
    example:
      "Rural 15%, Semi-urban 20%, Urban 40%, Metropolitan 25% (the four should sum to 100%).",
  },
  "C.P1.EI.8": {
    attribute: "Fairness to customers & suppliers",
    order: 8,
    definition:
      "Number of days of accounts payable = (Accounts payable × 365) / Cost of goods and services procured. A proxy for how promptly suppliers are paid.",
    example:
      "Accounts payable ₹5 crore, cost of goods/services procured ₹40 crore → (5 × 365) / 40 = 46 days.",
  },
  "C.P9.EI.7": {
    attribute: "Fairness to customers & suppliers",
    order: 8,
    definition:
      "Number of data-breach instances, the percentage involving personally identifiable information (PII) of customers, and the impact of those breaches.",
    example:
      "2 breaches in the year, 1 involving customer PII → 50% involving PII.",
  },
  "C.P1.EI.9": {
    attribute: "Openness of business",
    order: 9,
    definition:
      "Concentration of purchases and sales via trading houses and dealers, plus the share of related-party transactions (RPTs) in purchases, sales, loans & advances and investments.",
    example:
      "Purchases from trading houses = 30% of total purchases; sales to related parties = 12% of total sales.",
  },
};

export function coreGuide(questionKey: string): CoreGuide | undefined {
  return CORE_GUIDANCE[questionKey];
}

/** Cross-framework tags shown on each KPI (indicative crosswalk). */
export interface FrameworkTags {
  brsrPrinciple: number;
  gri?: string;
  issb?: string;
  sdg?: string;
}

export const FRAMEWORK_TAGS: Record<string, FrameworkTags> = {
  "C.P6.EI.7": { brsrPrinciple: 6, gri: "GRI 305", issb: "IFRS S2", sdg: "SDG 13" },
  "C.P6.EI.3": { brsrPrinciple: 6, gri: "GRI 303", sdg: "SDG 6" },
  "C.P6.EI.1": { brsrPrinciple: 6, gri: "GRI 302", issb: "IFRS S2", sdg: "SDG 7" },
  "C.P6.EI.9": { brsrPrinciple: 6, gri: "GRI 306", sdg: "SDG 12" },
  "C.P3.EI.1c": { brsrPrinciple: 3, gri: "GRI 401", sdg: "SDG 8" },
  "C.P3.EI.11": { brsrPrinciple: 3, gri: "GRI 403", sdg: "SDG 8" },
  "C.P5.EI.3b": { brsrPrinciple: 5, gri: "GRI 405", sdg: "SDG 5" },
  "C.P5.EI.7": { brsrPrinciple: 5, gri: "GRI 406", sdg: "SDG 5" },
  "C.P8.EI.4": { brsrPrinciple: 8, gri: "GRI 204", sdg: "SDG 8" },
  "C.P8.EI.5": { brsrPrinciple: 8, gri: "GRI 202", sdg: "SDG 8" },
  "C.P1.EI.8": { brsrPrinciple: 1, gri: "GRI 201", sdg: "SDG 8" },
  "C.P9.EI.7": { brsrPrinciple: 9, gri: "GRI 418", sdg: "SDG 16" },
  "C.P1.EI.9": { brsrPrinciple: 1, gri: "GRI 2-15", sdg: "SDG 16" },
};

export function frameworkTags(questionKey: string): FrameworkTags | undefined {
  return FRAMEWORK_TAGS[questionKey];
}
