import type { ModuleDef } from "@/lib/brsr/types";

export const modulesP3P5: ModuleDef[] = [
  {
    key: "C.P3",
    navLabel: "Principle 3: Employee Wellbeing",
    section: "C",
    principle: 3,
    title:
      "Principle 3: Businesses should respect and promote the well-being of all employees, including those in their value chains",
    intro:
      "Disclosures on employee and worker well-being, retirement benefits, health & safety management, training, grievance redressal and safety performance.",
    subsections: [
      {
        key: "C.P3.EI",
        title: "Essential Indicators",
        questions: [
          {
            key: "C.P3.EI.1a",
            code: "Essential Indicator 1a",
            section: "C",
            principle: 3,
            indicator: "essential",
            title: "Measures for the well-being of employees",
            help: "Provide the number and percentage of employees covered by each well-being measure. Percentage is computed as No. (B) divided by Total (A).",
            kind: "table",
            evidence: true,
            evidenceHint: "Insurance policies, benefit scheme documents",
            table: {
              columns: [
                { key: "cat", label: "Category", type: "text" },
                { key: "total", label: "Total (A)", type: "number" },
                { key: "hi_no", label: "Health insurance - No. (B)", type: "number" },
                { key: "hi_pct", label: "Health insurance - % (B/A)", type: "percentage", derived: { op: "ratioPct", num: "hi_no", den: "total" } },
                { key: "ai_no", label: "Accident insurance - No. (C)", type: "number" },
                { key: "ai_pct", label: "Accident insurance - % (C/A)", type: "percentage", derived: { op: "ratioPct", num: "ai_no", den: "total" } },
                { key: "mb_no", label: "Maternity benefits - No. (D)", type: "number" },
                { key: "mb_pct", label: "Maternity benefits - % (D/A)", type: "percentage", derived: { op: "ratioPct", num: "mb_no", den: "total" } },
                { key: "pb_no", label: "Paternity benefits - No. (E)", type: "number" },
                { key: "pb_pct", label: "Paternity benefits - % (E/A)", type: "percentage", derived: { op: "ratioPct", num: "pb_no", den: "total" } },
                { key: "dc_no", label: "Day-care facilities - No. (F)", type: "number" },
                { key: "dc_pct", label: "Day-care facilities - % (F/A)", type: "percentage", derived: { op: "ratioPct", num: "dc_no", den: "total" } },
              ],
              rows: [
                { key: "perm_m", label: "Male", group: "Permanent employees" },
                { key: "perm_f", label: "Female", group: "Permanent employees" },
                { key: "perm_t", label: "Total", group: "Permanent employees" },
                { key: "oth_m", label: "Male", group: "Other than Permanent employees" },
                { key: "oth_f", label: "Female", group: "Other than Permanent employees" },
                { key: "oth_t", label: "Total", group: "Other than Permanent employees" },
              ],
            },
          },
          {
            key: "C.P3.EI.1b",
            code: "Essential Indicator 1b",
            section: "C",
            principle: 3,
            indicator: "essential",
            title: "Measures for the well-being of workers",
            help: "Provide the number and percentage of workers covered by each well-being measure. Percentage is computed as No. (B) divided by Total (A).",
            kind: "table",
            evidence: true,
            evidenceHint: "Insurance policies, benefit scheme documents",
            table: {
              columns: [
                { key: "cat", label: "Category", type: "text" },
                { key: "total", label: "Total (A)", type: "number" },
                { key: "hi_no", label: "Health insurance - No. (B)", type: "number" },
                { key: "hi_pct", label: "Health insurance - % (B/A)", type: "percentage", derived: { op: "ratioPct", num: "hi_no", den: "total" } },
                { key: "ai_no", label: "Accident insurance - No. (C)", type: "number" },
                { key: "ai_pct", label: "Accident insurance - % (C/A)", type: "percentage", derived: { op: "ratioPct", num: "ai_no", den: "total" } },
                { key: "mb_no", label: "Maternity benefits - No. (D)", type: "number" },
                { key: "mb_pct", label: "Maternity benefits - % (D/A)", type: "percentage", derived: { op: "ratioPct", num: "mb_no", den: "total" } },
                { key: "pb_no", label: "Paternity benefits - No. (E)", type: "number" },
                { key: "pb_pct", label: "Paternity benefits - % (E/A)", type: "percentage", derived: { op: "ratioPct", num: "pb_no", den: "total" } },
                { key: "dc_no", label: "Day-care facilities - No. (F)", type: "number" },
                { key: "dc_pct", label: "Day-care facilities - % (F/A)", type: "percentage", derived: { op: "ratioPct", num: "dc_no", den: "total" } },
              ],
              rows: [
                { key: "perm_m", label: "Male", group: "Permanent workers" },
                { key: "perm_f", label: "Female", group: "Permanent workers" },
                { key: "perm_t", label: "Total", group: "Permanent workers" },
                { key: "oth_m", label: "Male", group: "Other than Permanent workers" },
                { key: "oth_f", label: "Female", group: "Other than Permanent workers" },
                { key: "oth_t", label: "Total", group: "Other than Permanent workers" },
              ],
            },
          },
          {
            key: "C.P3.EI.1c",
            code: "Essential Indicator 1c",
            section: "C",
            principle: 3,
            indicator: "essential",
            title: "Spending on measures towards well-being of employees and workers (including permanent and other than permanent) as a % of total revenue of the company",
            kind: "table",
            isCore: true,
            evidence: true,
            evidenceHint: "Audited financial statements",
            table: {
              perPeriod: true,
              columns: [
                { key: "wellbeing_pct", label: "Cost incurred on wellbeing measures as a % of total revenue of the company", type: "percentage" },
              ],
              rows: [
                { key: "spend", label: "Cost of wellbeing measures as % of total revenue" },
              ],
            },
          },
          {
            key: "C.P3.EI.2",
            code: "Essential Indicator 2",
            section: "C",
            principle: 3,
            indicator: "essential",
            title: "Details of retirement benefits, for Current FY and Previous Financial Year",
            kind: "table",
            evidence: true,
            evidenceHint: "PF / ESI / Gratuity challans and remittance proofs",
            table: {
              perPeriod: true,
              columns: [
                { key: "benefit", label: "Benefits", type: "text" },
                { key: "emp_pct", label: "No. of employees covered as a % of total employees", type: "percentage" },
                { key: "wrk_pct", label: "No. of workers covered as a % of total workers", type: "percentage" },
                { key: "deposited", label: "Deducted and deposited with the authority (Y/N/N.A.)", type: "enum", options: ["Y", "N", "N.A."] },
              ],
              rows: [
                { key: "pf", label: "PF" },
                { key: "gratuity", label: "Gratuity" },
                { key: "esi", label: "ESI" },
                { key: "others", label: "Others – please specify" },
              ],
            },
          },
          {
            key: "C.P3.EI.3",
            code: "Essential Indicator 3",
            section: "C",
            principle: 3,
            indicator: "essential",
            title: "Accessibility of workplaces",
            help: "Are the premises / offices of the entity accessible to differently abled employees and workers, as per the requirements of the Rights of Persons with Disabilities Act, 2016? If not, whether any steps are being taken by the entity in this regard.",
            kind: "narrative",
          },
          {
            key: "C.P3.EI.4",
            code: "Essential Indicator 4",
            section: "C",
            principle: 3,
            indicator: "essential",
            title: "Does the entity have an equal opportunity policy as per the Rights of Persons with Disabilities Act, 2016?",
            kind: "boolean",
            booleanDetail: "Web-link",
          },
          {
            key: "C.P3.EI.5",
            code: "Essential Indicator 5",
            section: "C",
            principle: 3,
            indicator: "essential",
            title: "Return to work and Retention rates of permanent employees and workers that took parental leave",
            kind: "table",
            table: {
              columns: [
                { key: "gender", label: "Gender", type: "text" },
                { key: "emp_rtw", label: "Permanent employees - Return to work rate", type: "percentage" },
                { key: "emp_ret", label: "Permanent employees - Retention rate", type: "percentage" },
                { key: "wrk_rtw", label: "Permanent workers - Return to work rate", type: "percentage" },
                { key: "wrk_ret", label: "Permanent workers - Retention rate", type: "percentage" },
              ],
              rows: [
                { key: "male", label: "Male" },
                { key: "female", label: "Female" },
                { key: "total", label: "Total" },
              ],
            },
          },
          {
            key: "C.P3.EI.6",
            code: "Essential Indicator 6",
            section: "C",
            principle: 3,
            indicator: "essential",
            title: "Is there a mechanism available to receive and redress grievances for the following categories of employees and worker?",
            help: "If yes, give details of the mechanism in brief.",
            kind: "table",
            table: {
              columns: [
                { key: "cat", label: "Category", type: "text" },
                { key: "yesno", label: "Yes/No", type: "boolean" },
                { key: "brief", label: "If Yes, then give details of the mechanism in brief", type: "text" },
              ],
              rows: [
                { key: "perm_wrk", label: "Permanent Workers" },
                { key: "oth_wrk", label: "Other than Permanent Workers" },
                { key: "perm_emp", label: "Permanent Employees" },
                { key: "oth_emp", label: "Other than Permanent Employees" },
              ],
            },
          },
          {
            key: "C.P3.EI.7",
            code: "Essential Indicator 7",
            section: "C",
            principle: 3,
            indicator: "essential",
            title: "Membership of employees and worker in association(s) or Unions recognised by the listed entity",
            kind: "table",
            table: {
              perPeriod: true,
              columns: [
                { key: "cat", label: "Category", type: "text" },
                { key: "total", label: "Total employees / workers in respective category (A)", type: "number" },
                { key: "member_no", label: "No. of employees / workers in respective category, who are part of association(s) or Union (B)", type: "number" },
                { key: "member_pct", label: "% (B/A)", type: "percentage", derived: { op: "ratioPct", num: "member_no", den: "total" } },
              ],
              rows: [
                { key: "emp_m", label: "Male", group: "Total Permanent Employees" },
                { key: "emp_f", label: "Female", group: "Total Permanent Employees" },
                { key: "wrk_m", label: "Male", group: "Total Permanent Workers" },
                { key: "wrk_f", label: "Female", group: "Total Permanent Workers" },
              ],
            },
          },
          {
            key: "C.P3.EI.8",
            code: "Essential Indicator 8",
            section: "C",
            principle: 3,
            indicator: "essential",
            title: "Details of training given to employees and workers",
            kind: "table",
            table: {
              perPeriod: true,
              columns: [
                { key: "cat", label: "Category", type: "text" },
                { key: "total", label: "Total (A)", type: "number" },
                { key: "hs_no", label: "On Health & safety measures - No. (B)", type: "number" },
                { key: "hs_pct", label: "% (B/A)", type: "percentage", derived: { op: "ratioPct", num: "hs_no", den: "total" } },
                { key: "skill_no", label: "On Skill upgradation - No. (C)", type: "number" },
                { key: "skill_pct", label: "% (C/A)", type: "percentage", derived: { op: "ratioPct", num: "skill_no", den: "total" } },
              ],
              rows: [
                { key: "emp_m", label: "Male", group: "Employees" },
                { key: "emp_f", label: "Female", group: "Employees" },
                { key: "emp_t", label: "Total", group: "Employees" },
                { key: "wrk_m", label: "Male", group: "Workers" },
                { key: "wrk_f", label: "Female", group: "Workers" },
                { key: "wrk_t", label: "Total", group: "Workers" },
              ],
            },
          },
          {
            key: "C.P3.EI.9",
            code: "Essential Indicator 9",
            section: "C",
            principle: 3,
            indicator: "essential",
            title: "Details of performance and career development reviews of employees and worker",
            kind: "table",
            table: {
              perPeriod: true,
              columns: [
                { key: "cat", label: "Category", type: "text" },
                { key: "total", label: "Total (A)", type: "number" },
                { key: "reviewed_no", label: "No. (B)", type: "number" },
                { key: "reviewed_pct", label: "% (B/A)", type: "percentage", derived: { op: "ratioPct", num: "reviewed_no", den: "total" } },
              ],
              rows: [
                { key: "emp_m", label: "Male", group: "Employees" },
                { key: "emp_f", label: "Female", group: "Employees" },
                { key: "emp_t", label: "Total", group: "Employees" },
                { key: "wrk_m", label: "Male", group: "Workers" },
                { key: "wrk_f", label: "Female", group: "Workers" },
                { key: "wrk_t", label: "Total", group: "Workers" },
              ],
            },
          },
          {
            key: "C.P3.EI.10",
            code: "Essential Indicator 10",
            section: "C",
            principle: 3,
            indicator: "essential",
            title: "Health and safety management system",
            kind: "fields",
            evidence: true,
            evidenceHint: "OHS management system certificate (e.g. ISO 45001)",
            fields: [
              { key: "ohs_system", label: "(a) Whether an occupational health and safety management system has been implemented by the entity?", type: "boolean", help: "If yes, the coverage such system." },
              { key: "ohs_coverage", label: "(a) If yes, what is the coverage of such system?", type: "longtext", optional: true },
              { key: "hazard_process", label: "(b) What are the processes used to identify work-related hazards and assess risks on a routine and non-routine basis by the entity?", type: "longtext" },
              { key: "report_unsafe", label: "(c) Whether you have processes for workers to report the work related hazards and to remove themselves from such risks?", type: "boolean" },
              { key: "medical_access", label: "(d) Do the employees / worker of the entity have access to non-occupational medical and healthcare services?", type: "boolean" },
            ],
          },
          {
            key: "C.P3.EI.11",
            code: "Essential Indicator 11",
            section: "C",
            principle: 3,
            indicator: "essential",
            title: "Details of safety related incidents",
            kind: "table",
            isCore: true,
            evidence: true,
            evidenceHint: "Safety incident records, LTIFR working, fatality reports",
            table: {
              perPeriod: true,
              columns: [
                { key: "param", label: "Safety Incident/Number", type: "text" },
                { key: "employees", label: "Employees", type: "number" },
                { key: "workers", label: "Workers (including contract workforce)", type: "number" },
              ],
              rows: [
                { key: "ltifr", label: "Lost Time Injury Frequency Rate (LTIFR) (per one million-person hours worked)" },
                { key: "recordable", label: "Total recordable work-related injuries" },
                { key: "fatalities", label: "No. of fatalities" },
                { key: "high_consequence", label: "High consequence work-related injury or ill-health (excluding fatalities)" },
              ],
            },
          },
          {
            key: "C.P3.EI.12",
            code: "Essential Indicator 12",
            section: "C",
            principle: 3,
            indicator: "essential",
            title: "Describe the measures taken by the entity to ensure a safe and healthy work place",
            kind: "narrative",
          },
          {
            key: "C.P3.EI.13",
            code: "Essential Indicator 13",
            section: "C",
            principle: 3,
            indicator: "essential",
            title: "Number of Complaints on the following made by employees and workers",
            kind: "table",
            table: {
              perPeriod: true,
              columns: [
                { key: "param", label: "Category", type: "text" },
                { key: "filed", label: "Filed during the year", type: "number" },
                { key: "pending", label: "Pending resolution at the end of year", type: "number" },
                { key: "remarks", label: "Remarks", type: "text" },
              ],
              rows: [
                { key: "working_conditions", label: "Working Conditions" },
                { key: "health_safety", label: "Health & Safety" },
              ],
            },
          },
          {
            key: "C.P3.EI.14",
            code: "Essential Indicator 14",
            section: "C",
            principle: 3,
            indicator: "essential",
            title: "Assessments for the year",
            help: "Percentage of your plants and offices that were assessed (by entity or statutory authorities or third parties).",
            kind: "fields",
            fields: [
              { key: "health_safety", label: "Health and safety practices", type: "percentage" },
              { key: "working_conditions", label: "Working Conditions", type: "percentage" },
            ],
          },
          {
            key: "C.P3.EI.15",
            code: "Essential Indicator 15",
            section: "C",
            principle: 3,
            indicator: "essential",
            title: "Provide details of any corrective action taken or underway to address safety-related incidents (if any) and on significant risks / concerns arising from assessments of health & safety practices and working conditions",
            kind: "narrative",
          },
        ],
      },
      {
        key: "C.P3.LI",
        title: "Leadership Indicators",
        questions: [
          {
            key: "C.P3.LI.1",
            code: "Leadership Indicator 1",
            section: "C",
            principle: 3,
            indicator: "leadership",
            title: "Does the entity extend any life insurance or any compensatory package in the event of death of employees and workers?",
            kind: "fields",
            fields: [
              { key: "employees", label: "(A) Employees", type: "boolean" },
              { key: "workers", label: "(B) Workers", type: "boolean" },
            ],
          },
          {
            key: "C.P3.LI.2",
            code: "Leadership Indicator 2",
            section: "C",
            principle: 3,
            indicator: "leadership",
            title: "Provide the measures undertaken by the entity to ensure that statutory dues have been deducted and deposited by the value chain partners",
            kind: "narrative",
          },
          {
            key: "C.P3.LI.3",
            code: "Leadership Indicator 3",
            section: "C",
            principle: 3,
            indicator: "leadership",
            title: "Provide the number of employees / workers having suffered high consequence work-related injury / ill-health / fatalities (as reported in Q11 of Essential Indicators above), who have been are rehabilitated and placed in suitable employment or whose family members have been placed in suitable employment",
            kind: "table",
            table: {
              perPeriod: true,
              columns: [
                { key: "cat", label: "Category", type: "text" },
                { key: "total_affected", label: "Total no. of affected employees / workers", type: "number" },
                { key: "rehabilitated", label: "No. of employees / workers that are rehabilitated and placed in suitable employment or whose family members have been placed in suitable employment", type: "number" },
              ],
              rows: [
                { key: "employees", label: "Employees" },
                { key: "workers", label: "Workers" },
              ],
            },
          },
          {
            key: "C.P3.LI.4",
            code: "Leadership Indicator 4",
            section: "C",
            principle: 3,
            indicator: "leadership",
            title: "Does the entity provide transition assistance programs to facilitate continued employability and the management of career endings resulting from retirement or termination of employment?",
            kind: "boolean",
          },
          {
            key: "C.P3.LI.5",
            code: "Leadership Indicator 5",
            section: "C",
            principle: 3,
            indicator: "leadership",
            title: "Details on assessment of value chain partners",
            help: "Percentage of value chain partners (by value of business done with such partners) that were assessed.",
            kind: "fields",
            fields: [
              { key: "health_safety", label: "Health and safety practices", type: "percentage" },
              { key: "working_conditions", label: "Working Conditions", type: "percentage" },
            ],
          },
          {
            key: "C.P3.LI.6",
            code: "Leadership Indicator 6",
            section: "C",
            principle: 3,
            indicator: "leadership",
            title: "Provide details of any corrective actions taken or underway to address significant risks / concerns arising from assessments of health and safety practices and working conditions of value chain partners",
            kind: "narrative",
          },
        ],
      },
    ],
  },
  {
    key: "C.P4",
    navLabel: "Principle 4: Stakeholder Responsiveness",
    section: "C",
    principle: 4,
    title:
      "Principle 4: Businesses should respect the interests of and be responsive to all its stakeholders",
    intro:
      "Disclosures on stakeholder identification, engagement channels and responsiveness to vulnerable and marginalised groups.",
    subsections: [
      {
        key: "C.P4.EI",
        title: "Essential Indicators",
        questions: [
          {
            key: "C.P4.EI.1",
            code: "Essential Indicator 1",
            section: "C",
            principle: 4,
            indicator: "essential",
            title: "Describe the processes for identifying key stakeholder groups of the entity",
            kind: "narrative",
          },
          {
            key: "C.P4.EI.2",
            code: "Essential Indicator 2",
            section: "C",
            principle: 4,
            indicator: "essential",
            title: "List stakeholder groups identified as key for your entity and the frequency of engagement with each stakeholder group",
            kind: "table",
            table: {
              dynamic: true,
              addLabel: "Add stakeholder group",
              columns: [
                { key: "group", label: "Stakeholder Group", type: "text" },
                { key: "vulnerable", label: "Whether identified as Vulnerable & Marginalized Group (Yes/No)", type: "boolean" },
                { key: "channels", label: "Channels of communication (Email, SMS, Newspaper, Pamphlets, Advertisement, Community Meetings, Notice Board, Website), Other", type: "text" },
                { key: "frequency", label: "Frequency of engagement (Annually/ Half yearly/ Quarterly / others – please specify)", type: "enum", options: ["Annually", "Half-yearly", "Quarterly", "Others"] },
                { key: "purpose", label: "Purpose and scope of engagement including key topics and concerns raised during such engagement", type: "text" },
              ],
            },
          },
        ],
      },
      {
        key: "C.P4.LI",
        title: "Leadership Indicators",
        questions: [
          {
            key: "C.P4.LI.1",
            code: "Leadership Indicator 1",
            section: "C",
            principle: 4,
            indicator: "leadership",
            title: "Provide the processes for consultation between stakeholders and the Board on economic, environmental, and social topics or if consultation is delegated, how is feedback from such consultations provided to the Board",
            kind: "narrative",
          },
          {
            key: "C.P4.LI.2",
            code: "Leadership Indicator 2",
            section: "C",
            principle: 4,
            indicator: "leadership",
            title: "Whether stakeholder consultation is used to support the identification and management of environmental, and social topics",
            kind: "boolean",
            booleanDetail: "Details of how inputs are incorporated",
          },
          {
            key: "C.P4.LI.3",
            code: "Leadership Indicator 3",
            section: "C",
            principle: 4,
            indicator: "leadership",
            title: "Provide details of instances of engagement with, and actions taken to, address the concerns of vulnerable/ marginalized stakeholder groups",
            kind: "narrative",
          },
        ],
      },
    ],
  },
  {
    key: "C.P5",
    navLabel: "Principle 5: Human Rights",
    section: "C",
    principle: 5,
    title: "Principle 5: Businesses should respect and promote human rights",
    intro:
      "Disclosures on human rights training, minimum wages, remuneration, grievance mechanisms, POSH complaints and human rights assessments.",
    subsections: [
      {
        key: "C.P5.EI",
        title: "Essential Indicators",
        questions: [
          {
            key: "C.P5.EI.1",
            code: "Essential Indicator 1",
            section: "C",
            principle: 5,
            indicator: "essential",
            title: "Employees and workers who have been provided training on human rights issues and policy(ies) of the entity",
            kind: "table",
            table: {
              perPeriod: true,
              columns: [
                { key: "cat", label: "Category", type: "text" },
                { key: "total", label: "Total (A)", type: "number" },
                { key: "covered_no", label: "No. of employees / workers covered (B)", type: "number" },
                { key: "covered_pct", label: "% (B/A)", type: "percentage", derived: { op: "ratioPct", num: "covered_no", den: "total" } },
              ],
              rows: [
                { key: "emp_perm", label: "Permanent", group: "Employees" },
                { key: "emp_oth", label: "Other than permanent", group: "Employees" },
                { key: "emp_t", label: "Total Employees", group: "Employees" },
                { key: "wrk_perm", label: "Permanent", group: "Workers" },
                { key: "wrk_oth", label: "Other than permanent", group: "Workers" },
                { key: "wrk_t", label: "Total Workers", group: "Workers" },
              ],
            },
          },
          {
            key: "C.P5.EI.2",
            code: "Essential Indicator 2",
            section: "C",
            principle: 5,
            indicator: "essential",
            title: "Details of minimum wages paid to employees and workers",
            kind: "table",
            evidence: true,
            evidenceHint: "Payroll records, wage registers",
            table: {
              perPeriod: true,
              columns: [
                { key: "cat", label: "Category", type: "text" },
                { key: "total", label: "Total (A)", type: "number" },
                { key: "equal_no", label: "Equal to Minimum Wage - No. (B)", type: "number" },
                { key: "equal_pct", label: "Equal to Minimum Wage - % (B/A)", type: "percentage", derived: { op: "ratioPct", num: "equal_no", den: "total" } },
                { key: "more_no", label: "More than Minimum Wage - No. (C)", type: "number" },
                { key: "more_pct", label: "More than Minimum Wage - % (C/A)", type: "percentage", derived: { op: "ratioPct", num: "more_no", den: "total" } },
              ],
              rows: [
                { key: "emp_perm_m", label: "Male", group: "Employees - Permanent" },
                { key: "emp_perm_f", label: "Female", group: "Employees - Permanent" },
                { key: "emp_oth_m", label: "Male", group: "Employees - Other than Permanent" },
                { key: "emp_oth_f", label: "Female", group: "Employees - Other than Permanent" },
                { key: "wrk_perm_m", label: "Male", group: "Workers - Permanent" },
                { key: "wrk_perm_f", label: "Female", group: "Workers - Permanent" },
                { key: "wrk_oth_m", label: "Male", group: "Workers - Other than Permanent" },
                { key: "wrk_oth_f", label: "Female", group: "Workers - Other than Permanent" },
              ],
            },
          },
          {
            key: "C.P5.EI.3a",
            code: "Essential Indicator 3a",
            section: "C",
            principle: 5,
            indicator: "essential",
            title: "Details of remuneration/salary/wages - Median remuneration / wages",
            kind: "table",
            evidence: true,
            evidenceHint: "Payroll records, wage registers",
            table: {
              columns: [
                { key: "cat", label: "Category", type: "text" },
                { key: "male_no", label: "Male - Number", type: "number" },
                { key: "male_median", label: "Male - Median remuneration/ salary/ wages of respective category", type: "currency" },
                { key: "female_no", label: "Female - Number", type: "number" },
                { key: "female_median", label: "Female - Median remuneration/ salary/ wages of respective category", type: "currency" },
              ],
              rows: [
                { key: "bod", label: "Board of Directors (BoD)" },
                { key: "kmp", label: "Key Managerial Personnel (KMP)" },
                { key: "employees", label: "Employees other than BoD and KMP" },
                { key: "workers", label: "Workers" },
              ],
            },
          },
          {
            key: "C.P5.EI.3b",
            code: "Essential Indicator 3b",
            section: "C",
            principle: 5,
            indicator: "essential",
            title: "Gross wages paid to females as % of total wages paid by the entity",
            kind: "table",
            isCore: true,
            evidence: true,
            evidenceHint: "Payroll records, wage registers",
            table: {
              perPeriod: true,
              columns: [
                { key: "female_wage_pct", label: "Gross wages paid to females as % of total wages", type: "percentage" },
              ],
              rows: [
                { key: "female_wages", label: "Gross wages paid to females as % of total wages" },
              ],
            },
          },
          {
            key: "C.P5.EI.4",
            code: "Essential Indicator 4",
            section: "C",
            principle: 5,
            indicator: "essential",
            title: "Do you have a focal point (Individual/ Committee) responsible for addressing human rights impacts or issues caused or contributed to by the business?",
            kind: "boolean",
          },
          {
            key: "C.P5.EI.5",
            code: "Essential Indicator 5",
            section: "C",
            principle: 5,
            indicator: "essential",
            title: "Describe the internal mechanisms in place to redress grievances related to human rights issues",
            kind: "narrative",
          },
          {
            key: "C.P5.EI.6",
            code: "Essential Indicator 6",
            section: "C",
            principle: 5,
            indicator: "essential",
            title: "Number of Complaints on the following made by employees and workers",
            kind: "table",
            table: {
              perPeriod: true,
              columns: [
                { key: "param", label: "Category", type: "text" },
                { key: "filed", label: "Filed during the year", type: "number" },
                { key: "pending", label: "Pending resolution at the end of year", type: "number" },
                { key: "remarks", label: "Remarks", type: "text" },
              ],
              rows: [
                { key: "sexual_harassment", label: "Sexual Harassment" },
                { key: "discrimination", label: "Discrimination at workplace" },
                { key: "child_labour", label: "Child Labour" },
                { key: "forced_labour", label: "Forced Labour/Involuntary Labour" },
                { key: "wages", label: "Wages" },
                { key: "other", label: "Other human rights related issues" },
              ],
            },
          },
          {
            key: "C.P5.EI.7",
            code: "Essential Indicator 7",
            section: "C",
            principle: 5,
            indicator: "essential",
            title: "Complaints filed under the Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013 (POSH)",
            kind: "table",
            isCore: true,
            evidence: true,
            evidenceHint: "POSH / Internal Committee (ICC) annual report",
            table: {
              perPeriod: true,
              columns: [
                { key: "param", label: "Particulars", type: "text" },
                { key: "value", label: "Number", type: "number" },
              ],
              rows: [
                { key: "total_reported", label: "Total Complaints reported under Sexual Harassment on of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013 (POSH)" },
                { key: "pct_female", label: "Complaints on POSH as a % of female employees / workers" },
                { key: "upheld", label: "Complaints on POSH upheld" },
              ],
            },
          },
          {
            key: "C.P5.EI.8",
            code: "Essential Indicator 8",
            section: "C",
            principle: 5,
            indicator: "essential",
            title: "Mechanisms to prevent adverse consequences to the complainant in discrimination and harassment cases",
            kind: "narrative",
          },
          {
            key: "C.P5.EI.9",
            code: "Essential Indicator 9",
            section: "C",
            principle: 5,
            indicator: "essential",
            title: "Do human rights requirements form part of your business agreements and contracts?",
            kind: "boolean",
          },
          {
            key: "C.P5.EI.10",
            code: "Essential Indicator 10",
            section: "C",
            principle: 5,
            indicator: "essential",
            title: "Assessments for the year",
            help: "Percentage of your plants and offices that were assessed (by entity or statutory authorities or third parties).",
            kind: "fields",
            fields: [
              { key: "child_labour", label: "Child labour", type: "percentage" },
              { key: "forced_labour", label: "Forced/involuntary labour", type: "percentage" },
              { key: "sexual_harassment", label: "Sexual harassment", type: "percentage" },
              { key: "discrimination", label: "Discrimination at workplace", type: "percentage" },
              { key: "wages", label: "Wages", type: "percentage" },
              { key: "others", label: "Others – please specify", type: "percentage", optional: true },
            ],
          },
          {
            key: "C.P5.EI.11",
            code: "Essential Indicator 11",
            section: "C",
            principle: 5,
            indicator: "essential",
            title: "Provide details of any corrective actions taken or underway to address significant risks / concerns arising from the assessments at Question 10 above",
            kind: "narrative",
          },
        ],
      },
      {
        key: "C.P5.LI",
        title: "Leadership Indicators",
        questions: [
          {
            key: "C.P5.LI.1",
            code: "Leadership Indicator 1",
            section: "C",
            principle: 5,
            indicator: "leadership",
            title: "Details of a business process being modified / introduced as a result of addressing human rights grievances/complaints",
            kind: "narrative",
          },
          {
            key: "C.P5.LI.2",
            code: "Leadership Indicator 2",
            section: "C",
            principle: 5,
            indicator: "leadership",
            title: "Details of the scope and coverage of any Human rights due-diligence conducted",
            kind: "narrative",
          },
          {
            key: "C.P5.LI.3",
            code: "Leadership Indicator 3",
            section: "C",
            principle: 5,
            indicator: "leadership",
            title: "Is the premise/office of the entity accessible to differently abled visitors, as per the requirements of the Rights of Persons with Disabilities Act, 2016?",
            kind: "boolean",
          },
          {
            key: "C.P5.LI.4",
            code: "Leadership Indicator 4",
            section: "C",
            principle: 5,
            indicator: "leadership",
            title: "Details on assessment of value chain partners",
            help: "Percentage of value chain partners (by value of business done with such partners) that were assessed.",
            kind: "fields",
            fields: [
              { key: "sexual_harassment", label: "Sexual Harassment", type: "percentage" },
              { key: "discrimination", label: "Discrimination at workplace", type: "percentage" },
              { key: "child_labour", label: "Child Labour", type: "percentage" },
              { key: "forced_labour", label: "Forced Labour/Involuntary Labour", type: "percentage" },
              { key: "wages", label: "Wages", type: "percentage" },
              { key: "others", label: "Others – please specify", type: "percentage", optional: true },
            ],
          },
          {
            key: "C.P5.LI.5",
            code: "Leadership Indicator 5",
            section: "C",
            principle: 5,
            indicator: "leadership",
            title: "Provide details of any corrective actions taken or underway to address significant risks / concerns arising from the assessments at Question 4 above",
            kind: "narrative",
          },
        ],
      },
    ],
  },
];
